export const data = [
    {
      announcementDate: "22-Jan-2023",
      description: "Desc",
      impactedServices: "Service",
      type: "Planned Maintenace",
      environment: "PROD",
      startDate: "22-Jan-2023",
      endDate: "22-Jan-2023",
    },
    {
        announcementDate: "22-Jan-2023",
        description: "Desc",
        impactedServices: "Service",
        type: "Planned Maintenace",
        environment: "STAGE",
        startDate: "22-Jan-2023",
        endDate: "22-Jan-2023",
      },
      {
        announcementDate: "22-Jan-2023",
        description: "Desc",
        impactedServices: "Service",
        type: "Planned Maintenace",
        environment: "INT",
        startDate: "22-Jan-2023",
        endDate: "22-Jan-2023",
      },{
        announcementDate: "22-Jan-2023",
        description: "Desc",
        impactedServices: "Service",
        type: "Planned Maintenace",
        environment: "PROD",
        startDate: "22-Jan-2023",
        endDate: "22-Jan-2023",
      },
      {
          announcementDate: "22-Jan-2023",
          description: "Desc",
          impactedServices: "Service",
          type: "Planned Maintenace",
          environment: "STAGE",
          startDate: "22-Jan-2023",
          endDate: "22-Jan-2023",
        },
        {
          announcementDate: "22-Jan-2023",
          description: "Desc",
          impactedServices: "Service",
          type: "Planned Maintenace",
          environment: "INT",
          startDate: "22-Jan-2023",
          endDate: "22-Jan-2023",
        },{
            announcementDate: "22-Jan-2023",
            description: "Desc",
            impactedServices: "Service",
            type: "Planned Maintenace",
            environment: "PROD",
            startDate: "22-Jan-2023",
            endDate: "22-Jan-2023",
          },
          {
              announcementDate: "22-Jan-2023",
              description: "Desc",
              impactedServices: "Service",
              type: "Planned Maintenace",
              environment: "STAGE",
              startDate: "22-Jan-2023",
              endDate: "22-Jan-2023",
            },
            {
              announcementDate: "22-Jan-2023",
              description: "Desc",
              impactedServices: "Service",
              type: "Planned Maintenace",
              environment: "INT",
              startDate: "22-Jan-2023",
              endDate: "22-Jan-2023",
            }
  ];